export const NOTIF_TYPES = {
  // instant triggers
  FIRST_BID:               "FIRST_BID",
  BID_ACCEPTED:            "BID_ACCEPTED",
  BID_REJECTED:            "BID_REJECTED",
  SHIPMENT_EXPIRED_BID:    "SHIPMENT_EXPIRED_BID",
  PICKUP_CONFIRMED:        "PICKUP_CONFIRMED",
  DELIVERY_CONFIRMED:      "DELIVERY_CONFIRMED",
  PAYMENT_RECEIVED:        "PAYMENT_RECEIVED",
  RATING_RECEIVED:         "RATING_RECEIVED",
  SHIPMENT_CANCELLED_BID:  "SHIPMENT_CANCELLED_BID",

  // cron triggers
  BIDDING_DEADLINE_SOON:   "BIDDING_DEADLINE_SOON",
  BIDDING_DEADLINE_PASSED: "BIDDING_DEADLINE_PASSED",
  NO_ASSIGNMENT_REMINDER:  "NO_ASSIGNMENT_REMINDER",
  EXPIRY_WARNING:          "EXPIRY_WARNING",
  SHIPMENT_EXPIRED:        "SHIPMENT_EXPIRED",
  PICKUP_REMINDER:         "PICKUP_REMINDER",
  PAYMENT_REMINDER:        "PAYMENT_REMINDER",
  RATING_REMINDER:         "RATING_REMINDER",
};